// @generated by scripts/generate-catrender-covalent-radii.mjs; do not edit.
// Input: src/lib/element/data.ts
// Input Git blob: d28d96c24f29a98944f1ae806f5c002266075c86
// Byte-identical historical source: 4da4da53631c057bf486a996f463201cf707d8a6:src/lib/element/data.ts
// License notice: third_party/licenses/MatterViz-MIT.txt

pub(crate) fn covalent_radius(symbol: &str) -> Option<f64> {
    match symbol {
        "Ac" => Some(2.15),
        "Ag" => Some(1.45),
        "Al" => Some(1.21),
        "Am" => Some(1.8),
        "Ar" => Some(1.06),
        "As" => Some(1.19),
        "At" => Some(1.5),
        "Au" => Some(1.36),
        "B" => Some(0.84),
        "Ba" => Some(2.15),
        "Be" => Some(0.96),
        "Bi" => Some(1.48),
        "Br" => Some(1.2),
        "C" => Some(0.76),
        "Ca" => Some(1.76),
        "Cd" => Some(1.44),
        "Ce" => Some(2.04),
        "Cl" => Some(1.02),
        "Cm" => Some(1.69),
        "Co" => Some(1.26),
        "Cr" => Some(1.39),
        "Cs" => Some(2.44),
        "Cu" => Some(1.32),
        "Dy" => Some(1.92),
        "Er" => Some(1.89),
        "Eu" => Some(1.98),
        "F" => Some(0.57),
        "Fe" => Some(1.32),
        "Fr" => Some(2.6),
        "Ga" => Some(1.22),
        "Gd" => Some(1.96),
        "Ge" => Some(1.2),
        "H" => Some(0.31),
        "He" => Some(0.28),
        "Hf" => Some(1.75),
        "Hg" => Some(1.32),
        "Ho" => Some(1.92),
        "I" => Some(1.39),
        "In" => Some(1.42),
        "Ir" => Some(1.41),
        "K" => Some(2.03),
        "Kr" => Some(1.16),
        "La" => Some(2.07),
        "Li" => Some(1.28),
        "Lu" => Some(1.87),
        "Mg" => Some(1.41),
        "Mn" => Some(1.39),
        "Mo" => Some(1.54),
        "N" => Some(0.71),
        "Na" => Some(1.66),
        "Nb" => Some(1.64),
        "Nd" => Some(2.01),
        "Ne" => Some(0.58),
        "Ni" => Some(1.24),
        "Np" => Some(1.9),
        "O" => Some(0.66),
        "Os" => Some(1.44),
        "P" => Some(1.07),
        "Pa" => Some(2.0),
        "Pb" => Some(1.46),
        "Pd" => Some(1.39),
        "Pm" => Some(1.99),
        "Po" => Some(1.4),
        "Pr" => Some(2.03),
        "Pt" => Some(1.36),
        "Pu" => Some(1.87),
        "Ra" => Some(2.21),
        "Rb" => Some(2.2),
        "Re" => Some(1.51),
        "Rh" => Some(1.42),
        "Rn" => Some(1.5),
        "Ru" => Some(1.46),
        "S" => Some(1.05),
        "Sb" => Some(1.39),
        "Sc" => Some(1.7),
        "Se" => Some(1.2),
        "Si" => Some(1.11),
        "Sm" => Some(1.98),
        "Sn" => Some(1.39),
        "Sr" => Some(1.95),
        "Ta" => Some(1.7),
        "Tb" => Some(1.94),
        "Tc" => Some(1.47),
        "Te" => Some(1.38),
        "Th" => Some(2.06),
        "Ti" => Some(1.6),
        "Tl" => Some(1.45),
        "Tm" => Some(1.9),
        "U" => Some(1.96),
        "V" => Some(1.53),
        "W" => Some(1.62),
        "Xe" => Some(1.4),
        "Y" => Some(1.9),
        "Yb" => Some(1.87),
        "Zn" => Some(1.22),
        "Zr" => Some(1.75),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::covalent_radius;

    #[test]
    fn generated_radii_cover_light_halogen_and_heavy_elements() {
        assert_eq!(covalent_radius("H"), Some(0.31));
        assert_eq!(covalent_radius("C"), Some(0.76));
        assert_eq!(covalent_radius("I"), Some(1.39));
        assert_eq!(covalent_radius("Xe"), Some(1.40));
        assert_eq!(covalent_radius("not-an-element"), None);
    }
}
