"""Auto-generate SLURM job scripts for HPC tasks.

Uses config-driven templates. No hardcoded values.

Resolution order for each field:
  task params → config.hpc.job_defaults → built-in fallbacks
"""

from __future__ import annotations

from typing import Any

# Default SLURM template — all values are {{placeholders}}
_DEFAULT_TEMPLATE = """#!/bin/bash
#SBATCH --job-name={{job_name}}
#SBATCH --nodes={{nodes}}
#SBATCH --ntasks={{ntasks}}
#SBATCH --cpus-per-task={{cpus_per_task}}
#SBATCH --time={{walltime}}
#SBATCH --partition={{partition}}
#SBATCH --account={{account}}
#SBATCH --output=%j.out
#SBATCH --error=%j.err

{{module_loads}}
{{env_setup}}

cd {{work_dir}}
{{run_command}}
"""

# Engine → run command mapping
_ENGINE_COMMANDS: dict[str, str] = {
    "vasp": "srun vasp_std",
    "cp2k": "srun cp2k.popt",
    "orca": "python run_orca.py",
    "lammps": "python run_lammps.py",
    "mlp": "python run_mlp.py",
    "xtb": "python run_xtb.py",
    "sella": "python run_sella.py",
}


def generate_job_script(
    engine_key: str,
    work_dir: str,
    task: dict,
    params: dict,
    config: dict,
) -> str:
    """Build a complete SLURM job script from config + params.

    Returns a string with #SBATCH headers + run command.
    """
    hpc_cfg = config.get("hpc", {})
    job_defaults = hpc_cfg.get("job_defaults", {})

    # Template: task > config > built-in
    template = (
        params.get("job_script_template")
        or hpc_cfg.get("job_script_template")
        or _DEFAULT_TEMPLATE
    )

    # Resolve each field with priority: params > job_defaults > fallback
    def _get(key: str, fallback: str = "") -> str:
        val = params.get(key) or job_defaults.get(key) or fallback
        return str(val) if val else ""

    task_id = task.get("id", "")[:8]
    task_type = task.get("task_type", "unknown")

    # Run command: params > config > engine default
    run_command = (
        params.get("run_command")
        or hpc_cfg.get("run_commands", {}).get(engine_key)
        or _ENGINE_COMMANDS.get(engine_key, f"srun {engine_key}")
    )

    # Custodian override for VASP
    use_custodian = params.get("use_custodian", hpc_cfg.get("use_custodian", False))
    if engine_key == "vasp" and use_custodian:
        run_command = "python run_custodian.py"

    # VASP executable override (vasp_gam, vasp_ncl, etc.)
    if engine_key == "vasp" and not use_custodian:
        vasp_exe = params.get("vasp_executable")
        if vasp_exe and vasp_exe != "vasp_std":
            run_command = run_command.replace("vasp_std", vasp_exe)

    replacements = {
        "{{job_name}}": f"catgo-{task_type}-{task_id}",
        "{{work_dir}}": work_dir,
        "{{nodes}}": _get("nodes", "1"),
        "{{ntasks}}": _get("ntasks", "32"),
        "{{cpus_per_task}}": _get("cpus_per_task", "1"),
        "{{walltime}}": _get("walltime", "24:00:00"),
        "{{partition}}": _get("partition", "shared"),
        "{{account}}": _get("account", ""),
        "{{module_loads}}": _get("module_loads", ""),
        "{{env_setup}}": _get("env_setup", ""),
        "{{run_command}}": run_command,
    }

    script = template
    for key, val in replacements.items():
        script = script.replace(key, val)

    # Clean up empty #SBATCH lines (e.g., --account= when no account)
    lines = []
    for line in script.split("\n"):
        if line.startswith("#SBATCH") and line.endswith("="):
            continue  # Skip empty SBATCH directives
        lines.append(line)

    result = "\n".join(lines)

    # If the template was a user-provided preamble without {{run_command}} placeholder,
    # append cd + run_command so the job actually executes
    if "{{run_command}}" not in template:
        result = result.rstrip() + f"\n\ncd {work_dir}\n{run_command}\n"

    return result


def generate_custodian_script(
    vasp_command: str,
    params: dict,
    config: dict,
) -> str | None:
    """Generate run_custodian.py if custodian is enabled. Returns None otherwise."""
    hpc_cfg = config.get("hpc", {})
    use_custodian = params.get("use_custodian", hpc_cfg.get("use_custodian", False))
    if not use_custodian:
        return None

    max_errors = params.get("custodian_max_errors", hpc_cfg.get("custodian_max_errors", 5))

    return f'''#!/usr/bin/env python3
"""Run VASP with custodian error handling. Generated by CatGo v2 engine."""
import logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s",
                    handlers=[logging.FileHandler("custodian_run.log"), logging.StreamHandler()])

from custodian.custodian import Custodian
from custodian.vasp.handlers import (
    VaspErrorHandler, MeshSymmetryErrorHandler, UnconvergedErrorHandler,
    NonConvergingErrorHandler, PotimErrorHandler, FrozenJobErrorHandler,
    StdErrHandler, WalltimeHandler,
)
from custodian.vasp.jobs import VaspJob

vasp_cmd = "{vasp_command}".split()
handlers = [
    VaspErrorHandler(), MeshSymmetryErrorHandler(), UnconvergedErrorHandler(),
    NonConvergingErrorHandler(), PotimErrorHandler(), FrozenJobErrorHandler(),
    StdErrHandler(), WalltimeHandler(),
]
jobs = [VaspJob(vasp_cmd, output_file="vasp.out", stderr_file="std_err.txt")]
c = Custodian(handlers, jobs, max_errors={max_errors})
c.run()
'''
