[pytest]
asyncio_mode = auto
filterwarnings =
    error::DeprecationWarning
    error::FutureWarning
    error::RuntimeWarning
    error::UserWarning
    ignore:^Setting the shape on a NumPy array has been deprecated in NumPy 2\.5\.\nAs an alternative, you can create a new view using np\.reshape \(with copy=False if needed\)\.$:DeprecationWarning:ase\.atoms
    ignore:^Optimal rotation is not uniquely or poorly defined for the given sets of vectors\.$:UserWarning:scipy\.spatial\.transform\._rotation
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks integration tests
